### ISSUE TITLE
[CRASH] Twilight Forest exception ticking world crash

### ISSUE THREAD

**Issue by bubububububububububububububububu** [Rebirth-of-the-Night/Rebirth-Of-The-Night#640]
I got the queen ghast tear, i made the twilight forest portal model, i teleported to the dimension, and the game crashed
**To Reproduce**

1. Get the queen ghast tear
2. Make the twilight forest portal model
3. Light the portal
4. Enter the portal

**Crash Log**

**https://haste.antti.codes/hifizezune.mccrash**

**Info (please complete the following information):**
 - Modpack Version: 1.12.2
 - Server or Singleplayer: SinglePlayer
 - Version the world was created on: 3.0 Beta

**Additional context**
I need to create a new world to continue playing the game, so please fix this

**Comment by democat3457** [comment]
which beta version

**Comment by democat3457** [comment]
bc it *should* be fixed in beta 3

**Comment by kil0byt3** [comment]
> bc it _should_ be fixed in beta 3, esp on singleplayer

Still an issue on latest dev ver; something with mob spawning from my understanding? Can you take a look? 

[debug.log](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6032128/debug.log)

**Comment by democat3457** [comment]
@kil0byt3 that log is actually a different crash than the one reported here

**Comment by kil0byt3** [comment]
fuck

**Comment by SenatorSupreme** [comment]
Temp fix in B5

**Comment by democat3457** [comment]
partial dupe - same exception, different times of occurrence
