### ISSUE TITLE
[CRASH] Various server issues

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#738]
**Describe the crash**
There are various server issues being caused by ticking entities, cascading worldgen lag, and lastly a server timeout/freeze due to _an arrow being shot by a skeleton into a BWM extended hemp rope from a pulley in a barn._ 

**To Reproduce**  
1. Run a RoTN 3.0 Beta 5 server and play for a while. 
2. Check server logs which are spammed with these errors. 

**Crash Log**
[Various Server Errors.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6339690/Various.Server.Errors.txt)

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [X] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 5
   - [ ] Other: 

**Additional context**
The `rats:illager_piper` was the usual cause for the ticking entities error while cascading worldgen lag was caused by the mods shown in the log above. The BWM barn's pulley rope is a likely culprit of the last timeout/crash the server encountered before the owner had to restart it.

**Comment by CalaMariGold** [comment]
`java.lang.OutOfMemoryError: Java heap space`

How much RAM do you have allocated? Not a Java expert but I think that error means your server is running out of memory

**Comment by SenatorSupreme** [comment]
It has 12gb allocated, which should be enough for any semi-reasonable amount of people. Unless they have 8+ people and something massive happened, it shouldn't be running out of RAM.

I've also seen them play and it's usually not past 3-4 people, but they may have had more this time.

**Comment by KaleThyself** [comment]
> edit: They did have 6 people, but it was only for about 3 minutes and the lag was present before and after they joined/left. Even after another person left there was constant tick lag.

Correct.

**Comment by democat3457** [comment]
> rats:illager_piper

Probably due to the Arcane World bug at #539

**Comment by KaleThyself** [comment]
Ticking entity issue on the same server causing a Java heap space (out of memory) error:
[ticking entity.txt](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6412928/ticking.entity.txt)

**Comment by democat3457** [comment]
wow now it's esm

**Comment by democat3457** [comment]
@KaleThyself 
![image](https://user-images.githubusercontent.com/32407067/116887967-8661f700-abf0-11eb-92e6-d018f1ebd3bb.png)

**Comment by KaleThyself** [comment]
> 
> 
> @KaleThyself
> ![image](https://user-images.githubusercontent.com/32407067/116887967-8661f700-abf0-11eb-92e6-d018f1ebd3bb.png)

I acquired the entire log from the server host if it helps. (6MB) 
Players affected in the logs: `xXxKillzonexXx`, `Bonze17`
[2021-05-02-7.log](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6417865/2021-05-02-7.log)

**Comment by KaleThyself** [comment]
@democat3457 
Lag Profiler Update: 
![image](https://user-images.githubusercontent.com/50285548/117933254-37822480-b2b6-11eb-9290-de1a4c903b8c.png)
This is the log that corresponds to the lag profile performed above: 
[lag_heapdump_log.log](https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/files/6464136/lag_heapdump_log.log)

**Comment by democat3457** [comment]
The original ticking entities error on the illager should be fixed by #760

**Comment by KaleThyself** [comment]
> 
> 
> Hey, also running a 3.0 Beta 5 server. Any news in this regard/things that could be done to potentially lessen lag? My server has reached 124 days of in game playtime, and the lag has gotten to the point that any travel through chunks faster than just sprinting will just about bring the server to its knees. No amount of restarting, or other methods has resolved this issue.

Unfortunately it's futile at the moment. I've tried every fix that worked before as well as clearing all entities, but the lag still persists. The lag only occurs in the overworld while other dimensions are fine as long as the overworld is not loaded. You're better off rolling back to an old Beta 4 world as Beta 5 is unplayable after making progress in RoTN.

**Comment by FamiliarPings** [comment]
That is a rip. Understandable though, it is a beta. Currently looking at ditching the world and going to 2.77.5. Players on the server were well aware that there could be game ending glitches in the beta, but we wanted to try it out anyway.

As an idea though, have you tried removing the Epic Siege mod entirely? Yeah, it'd be a rather central part of the pack gone, but given that the only invasion is zombies at the moment anyway, might not be all that big of a loss.

**Comment by KaleThyself** [comment]
> 
> 
> That is a rip. Understandable though, it is a beta. Currently looking at ditching the world and going to 2.77.5. Players on the server were well aware that there could be game ending glitches in the beta, but we wanted to try it out anyway.
> 
> As an idea though, have you tried removing the Epic Siege mod entirely? Yeah, it'd be a rather central part of the pack gone, but given that the only invasion is zombies at the moment anyway, might not be all that big of a loss.

No can do since removing one mod such as the core ESM will cause many other mods to break to my knowledge. However, if you're willing to take the chance for the sake of your world, fill me in on the results.

**Comment by FamiliarPings** [comment]
I imagined that might be the case, damn. @developers have you guys put a warning somewhere near the beta 5 download about servers? I imagine you have, just suggesting. This is gotta be the worst bug, cause its inevitable, and hits right when you're really picking up steam in the pack :/

**Comment by KaleThyself** [comment]
Issues described above are no longer present in v.3.1.1a.
